-- Création des deux bases de données
CREATE DATABASE IF NOT EXISTS ELECTRICITY_RAW;
CREATE DATABASE IF NOT EXISTS ELECTRICITY_DBT;

-- Création des schémas Bronze (données brutes)
CREATE SCHEMA IF NOT EXISTS ELECTRICITY_RAW.ECO2MIX;

-- Création des schémas dbt (Silver et Gold)
CREATE SCHEMA IF NOT EXISTS ELECTRICITY_DBT.STAGING;
CREATE SCHEMA IF NOT EXISTS ELECTRICITY_DBT.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS ELECTRICITY_DBT.MARTS;